### ISSUE TITLE
`From commandline` command error

### ISSUE THREAD

**Issue by laxatives** [chakki-works/sumeval#1]
```
$ sumeval r-nlb "I'm living New York its my home town so awesome" "My home town is awesome"
Traceback (most recent call last):
  File "/usr/local/bin/sumeval", line 9, in <module>
    load_entry_point('sumeval==0.1.4', 'console_scripts', 'sumeval')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2697, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2370, in load
    return self.resolve()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2376, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Python/2.7/site-packages/sumeval/cli/sum_eval.py", line 10
    score_desc: "ex: To calculate ROUGE-N, L, BE => 'r-nlb'",
```

**Comment by icoxfog417** [comment]
Thank you for the issue & PR(#2)! I merged the proposed fix.
But [sumeval only supports Python3](https://github.com/chakki-works/sumeval/blob/master/setup.py#L45). So running on Python2 will cause some issues.
